name: GitHub Pages

on:
  push:
    branches:
      - main2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main docs repo
        uses: actions/checkout@v3
      - name: Setup Docusaurus
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Build website
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn build --config enterprise.config.js --out-dir build_enterprise
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      - name: Copy enterprise build output to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: ent-pages
          FOLDER: build_enterprise
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
